Blog App: validations and model specs
fmanimashaun/myblog pull request #5
Opened 2023-12-02 16:31 UTC by fmanimashaun

2023-12-02 21:25 UTC, KDlamini requested changes
### Hi @fmanimashaun 🙋‍♀️,  

Great work so far! 💯 
You have done a great job adding model validations and specs. 🎊 🥳 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Good PR title and description
✔️  Well-documented and professional README
✔️  Model validations for User and Post are included
✔️  Specs for model validations are well implemented

### To Improve 🔧 

- In the future, please be consistent with how you write commit messages.  It would be best to follow the best practices for writing all commit messages. Kindly ensure that all commit messages start with a capital letter, like you would any sentence, and are descriptive of the purpose of the commit.
- README : Tests - Since this milestone is for validation specs, it would be best to include the command necessary to run the tests in the README Getting Started section.

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-02 21:25 UTC, KDlamini commented on spec/models/user_spec.rb
Great job with the model validations and specs. Thank you for showing great knowledge and dedication in adequately testing the app models. 🚀 

Kindly note that all public methods in the models should be tested. According to the Blog App milestones, there should be `update_posts_counter`, `update_comments_counter`, and `update_likes_counter` methods in the Post, Comment, and Like models, respectively. However, I could not find these methods in your models.

- These methods should present in your models and should be tested. The tests should check if the `create` action increments the relative model counter by 1. Kindly make sure that these tests are implemented.


Otherwise, well done with the rest of the passing tests.

![image](https://github.com/fmanimashaun/myblog/assets/38088818/8c1982c1-aaf4-45f4-a0fc-b158d5b1e74d)

2023-12-03 00:43 UTC, fmanimashaun commented on spec/models/user_spec.rb
Thanks for the observation: however, i have updated my models accordingly:

I have set the counter_cache option in your belongs_to associations, thus, rails will automatically handle the updating of the counter columns (posts_counter, likes_counter, comments_counter). As such, no need to manually define an update_counter method in the  models. 

In addition, I have add the unit test to test this functionality in all models as required

2023-12-03 03:18 UTC, prolajumokeoni approved these changes
Hi @fmanimashaun 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
✔️ added validations for models
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-03 03:22 UTC, merged

2023-12-03 17:28 UTC, nicupop729 reviewed
Hello @fmanimashaun  👋,

_This is an additional review as a result of the second opinion request._

As you asked for a normal review after requesting a second opinion review and due to the consequent approval, this second opinion review is redundant.

Keep rocking 🚀!